name: Publish DPsim package to Python Package Index (PyPI)

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-sdist:
    name: Build DPsim source distribution
    runs-on: ubuntu-24.04
    container: sogno/dpsim:dev
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build DPsim source distribution
      shell: bash
      run: python3 -m build --sdist --outdir dist/

    - name: Archive Python source distribution
      uses: actions/upload-artifact@v4
      with:
        name: dist-source
        path: dist/

  build-wheels:
    name: Build DPsim wheels
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build DPsim wheels for all supported Python versions
      uses: pypa/cibuildwheel@v2.23.2
      with:
        output-dir: dist

    - name: Archive Python wheels
      uses: actions/upload-artifact@v4
      with:
        name: dist-wheels
        path: dist/

  publish:
    name: Publish wheels and source distribution to PyPI
    runs-on: ubuntu-24.04
    needs:
    - build-wheels
    - build-sdist

    steps:
    - name: Download artifacts from build jobs
      uses: actions/download-artifact@v4
      with:
        pattern: dist-*
        merge-multiple: true
        path: dist/

    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@v1.12.4
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true

    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@v1.12.4
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
